---
configure_terminal: yes
configure_osx: yes
configure_dotfiles: yes

dotfiles_repo: https://github.com/DemisR/dotfiles.git
dotfiles_repo_accept_hostkey: yes
dotfiles_repo_local_destination: ~/dotfiles
dotfiles_files:
  - .aliases
  - .zshrc
  - .gitconfig
  - .gitignore_global
  - .vimrc
  - .vim
  - .osx
  - .functions

homebrew_installed_packages:
# Dev
  # *** Java ***
  - jenv # Manage your Java environment
  - maven # Java-based project management
  # *** GO lang ***
  - go
  # *** Python ***
  - python
  - python3
  - pipenv # Python dependency management tool
  # *** Javascript ***
  - volta # Manage multiple Node.js versions (replace nvm)
  - node # Node JS
  # Shell Utilities 
  - mas # Mac App Store command-line interface
  - git
  - httpie # User-friendly cURL replacement (command-line HTTP client)
  - jq # Lightweight and flexible command-line JSON processor
  - sqlite # Command-line interface for SQLite
  - coreutils # GNU File, Shell, and Text utilities
  - tree # Display directories as trees 
  - csshx # Cluster ssh tool for Terminal.app
  - fzf # Command-line fuzzy finder written in Go
  - whatmask # Network settings helper
  - wget # Internet file retriever
  - nmap # Port scanning utility
  - ssh-copy-id # Add a public key to a remote machine's authorized_keys file
  - openssl # OpenSSL GIO module for glib
  - pandoc # Swiss-army knife of markup format conversion
  - telnet # User interface to the TELNET protocol
  - sshuttle # Proxy server that works as a poor man's VPN
  - tldr # Simplified and community-driven man pages
  - tmux # Terminal multiplexer
  - bat # Clone of cat(1) with syntax highlighting and Git integration
  - awscli # AWS CLI
  - ripgrep # Search tool like grep but much faster


homebrew_taps:
  - homebrew/core
  - adoptopenjdk/openjdk

homebrew_cask_appdir: /Applications
homebrew_cask_apps:
  - kite
  - slack # Team communication and collaboration software
  - notion
# Browsers
  - brave-browser
# Utilities
  - vlc # VLC media player
  - kap # Open-source screen recorder built with web technology
  - spotify
  - cyberduck # browser FTP, SFTP, s3,...
  - dropbox # Client for the Dropbox cloud storage service
  - the-unarchiver # Unpacks archive files
# DevOps tools
  - docker
  - vagrant
  - virtualbox
# Dev environment
  - phantomjs
  - adoptopenjdk8 #Java JDK
  - adoptopenjdk11 #Java JDK
  - sourcetree # Graphical client for Git version control
  - postman # Collaboration platform for API development
  - insomnia # postman alternative
  - visual-studio-code
  - open-in-code # Finder toolbar app to open current folder in Visual Studio Code
# Databases
  - postico # GUI client for PostgreSQL databases
  - tableplus # friendly GUI tool for relational databases
# Quick look plugins
  - qlcolorcode # Quick Look plug-in that renders source code with syntax highlighting
  - qlstephen # A QuickLook plugin that lets you view plain text files without a file extension
  - qlmarkdown
  - quicklook-json
  - quicklook-csv
  - go2shell # Opens a terminal window to the current directory in Finder.

# See `geerlingguy.mas` role documentation for usage instructions.
mas_installed_app_ids:
  - 425424353 # The Unarchiver
  - 937984704 # Amphetamine
  - 1199502670 # Teampaper Snap
  - 425955336 # Skitch
  - 472226235 # LanScan
  - 973213640 # MSG Viewer for Outlook
  - 1091189122 # Bear
  - 568494494 # Pocket
  - 409201541 # Pages
  - 409183694 # Keynote
  - 409203825 # Numbers
  - 1295203466 # Microsoft Remote Desktop
  - 513610341 # com.peacockmedia.integrity
  - 1176895641 # Spark Email App by Readdle
  - 1333542190 # 1password
  - 803453959 # Slack
  - 1510445899 # Meeter
  - 1509590766 # MuteKey